<script src="{{ asset('assetsAdmin/vendor/bootstrap/js/bootstrap.bundle.js') }}"></script>
<script src="{{ asset('assetsAdmin/vendor/php-email-form/validate.js') }}"></script>
<script src="{{ asset('assetsAdmin/vendor/quill/quill.min.js') }}"></script>
<script src="{{ asset('assetsAdmin/vendor/tinymce/tinymce.min.js') }}"></script>
<script src="{{ asset('assetsAdmin/vendor/simple-datatables/simple-datatables.js') }}"></script>
<script src="{{ asset('assetsAdmin/vendor/chart.js') }}/chart.min.js') }}"></script>
<script src="{{ asset('assetsAdmin/vendor/apexcharts/apexcharts.min.js') }}"></script>
<script src="{{ asset('assetsAdmin/vendor/echarts/echarts.min.js') }}"></script>
<script src="{{ asset('assetsAdmin/js/main.js') }}"></script>